INSERT INTO RESTAURANT(ID,NAME,CONTACT,LOCATION, ZIPCODE) VALUES (1,'Sergios','112233','New York', 1000);
INSERT INTO RESTAURANT(ID,NAME,CONTACT,LOCATION, ZIPCODE) VALUES (2,'Alpine','123344','Helsinki', 1001);
INSERT INTO RESTAURANT(ID,NAME,CONTACT,LOCATION, ZIPCODE) VALUES (3,'Abdul','212233','Saudi Arabia', 1101);

INSERT INTO USERS(ID,NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES (1,'Bilbo Baggins','London','Westminster',112233,true,false,false);
INSERT INTO USERS(ID,NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES (2,'Frodo Baggins','New Zealand','Chirstchurch',221133,true,true,false);
INSERT INTO USERS(ID,NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES (3,'Samwise','Ireland','Dublin',332211,true,false,true);

INSERT INTO DINING_REVIEW(ID,REVIEWED_BY,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENTARY,REVIEW_STATUS) 
  VALUES (1,'BigJock',2,3,5,5,'Good food','PENDING');
INSERT INTO DINING_REVIEW(ID,REVIEWED_BY,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENTARY,REVIEW_STATUS) 
  VALUES (2,'NorthernSoul',1,4,5,3,'Okay food','APPROVED');
INSERT INTO DINING_REVIEW(ID,REVIEWED_BY,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENTARY,REVIEW_STATUS) 
  VALUES (3,'BilboBaggins',3,3,3,3,'Good Service','REJECTED');