INSERT INTO RESTAURANT(NAME,CONTACT,LOCATION, ZIPCODE) VALUES ('Sergios',112233,'New York', 1000);
INSERT INTO RESTAURANT(NAME,CONTACT,LOCATION, ZIPCODE) VALUES ('Alpine',123344,'Helsinki', 1001);
INSERT INTO RESTAURANT(NAME,CONTACT,LOCATION, ZIPCODE) VALUES ('Abdul',212233,'Saudi Arabia', 1101);

INSERT INTO USER(NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES ('Bilbo Baggins','London','Westminster',112233,true,false,false);
INSERT INTO USER(NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES ('Frodo Baggins','New Zealand','Chirstchurch',221133,true,true,false);
INSERT INTO USER(NAME,CITY,STATE,ZIPCODE,BOOL_PEANUT,BOOL_EGG, BOOL_DAIRY) 
  VALUES ('Samwise','Ireland','Dublin',332211,true,false,true);

INSERT INTO DINING_REVIEW(NAME,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT,REVIEW_STATUS) 
  VALUES ('Big Jock',2,3,5,5,'Good food','PENDING');
INSERT INTO DINING_REVIEW(NAME,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT,REVIEW_STATUS) 
  VALUES ('Northern Soul',1,4,5,3,'Okay food','APPROVED');
INSERT INTO DINING_REVIEW(NAME,RESTAURANT_ID,PEANUT_SCORE,EGG_SCORE,DAIRY_SCORE,COMMENT,REVIEW_STATUS) 
  VALUES ('Bilbo Baggins',3,3,3,3,'Good Service','REJECTED');